# -*- coding: utf-8 -*-
"""NaiaraAbrilUno

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_wrz9-HffTjUUzUedPeIGVKgrUrund5
"""

#cree una lista
notas = []

print("si queres salir pone -1")

while true:
  notas = int(input("ingrese nota de matematica"))
  notas = int(input("ingrese nota de historia"))
  notas = int(input(" ingrese nota de ed fisica"))

  if notas == -1:
   break


  if 0 <= and <= 10:
  notas.append

elif:
 print("la nota tiene q ser entre o y 10")

 #ahora calculo el promedio
elif len notas > 0:
promedio = sum(notas) / len(notas)
 print("tu promedio es", promedio)

elif:
promedio >= 7:
 print("aprobaste")

else:
 print("no aprobaste")